---
- name: ensure server can build package (Debian)
  apt: name=build-essential state=present
  when: ansible_os_family == 'Debian'

- name: ensure server can build package (RedHat)
  yum: name={{ item }} state=present
  with_items:
    - binutils
    - gcc
  when: ansible_os_family == 'RedHat'
