---
- name: ensure service is stopped before the config fie is updated
  service: name=vpnserver enabled=yes state=stopped

- name: disable DDnsClient (this only be done via config file)
  replace:
    dest: "{{ softether_install_path }}/vpn_server.config"
    regexp: '(declare DDnsClient\W+{\W+bool Disabled) (false)([^}]*)'
    replace: '\g<1> true\r\n\t'
  tags:
    - ddnsclient

- name: ensure service is enabled and started
  service: name=vpnserver enabled=yes state=started

- include: remotesyslog.yml
  when: softether_enable_syslog

- name: create batch configuration file
  template: src=batchconfig.vpn.j2 dest="{{ softether_install_path }}/batchconfig.vpn"
  notify:
    - reload vpn config
