---
- name: ensure service is stopped before the config fie is updated
  service: name=vpnserver enabled=yes state=stopped

- name: disable DDnsClient (this only be done via config file)
  replace:
    dest: "{{ softether_install_path }}/vpn_server.config"
    regexp: '(declare DDnsClient\W+{\W+bool Disabled) (false)([^}]*)'
    replace: '\g<1> true\r\n\t'

- name: ensure service is enabled and started
  service: name=vpnserver enabled=yes state=started

- name: configure syslog to handle udp input
  lineinfile:
    dest: "/etc/rsyslog.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: '^#module\(load="imudp"\)'
      line: 'module(load="imudp")'
    - regexp: '^#input\(type="imudp" port='
      line: '^input\(type="imudp" port="514"\)'

- name: restart syslog
  service: name=rsyslog state=restarted
