---
# tasks file for ansible-role-softether-server
- include: buildtools.yml

- name: setup tmp path
  file: path={{ softether_tmp_path }} state=directory

- name: copy answer file to run make non-interactively
  copy: src=make.answers dest={{ softether_tmp_path }}/make.answers

- name: download package
  get_url: url={{ softether_url }} dest="{{ softether_tmp_path }}/{{ softether_package_file }}"
  register: download

- name: extract vpnserver package
  unarchive:
    src: "{{ softether_tmp_path}}/{{ softether_package_file }}"
    dest: "{{ softether_install_prefix }}"
    copy: false
  when: download.changed or softether_force_build

- name: execute build
  shell: make < {{ softether_tmp_path }}/make.answers
  args:
    chdir: "{{ softether_install_path }}"
  when: download.changed or softether_force_build

- include: permissionfix.yml

- name: copy vpnserver init.d script
  template: src=vpnserver.initd.j2 dest=/etc/init.d/vpnserver mode=0755

- name: ensure service is stopped before the config fie is updated
  service: name=vpnserver enabled=yes state=stopped

- name: copy vpn server config
  template: src=vpn_server.config.j2 dest={{ softether_install_path }}/vpn_server.config backup=yes

- name: ensure service is enabled and started
  service: name=vpnserver enabled=yes state=started

