---
- name: fix permissions, directories
  file: state=directory path={{ softether_install_path }} mode=0700 recurse=yes

- name: fix permissions, executables
  file: state=file path={{ item }} mode=0700
  with_items:
    - "{{ softether_install_path }}/vpnserver"
    - "{{ softether_install_path }}/vpncmd"
